services:
  web:
    restart: unless-stopped
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - internal
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.budgetify.rule=(Host(`omen.local`) && PathPrefix(`/budgetify`))
      - traefik.http.routers.budgetify.entrypoints=web

networks:
  internal:
    internal: true
  traefik:
    external: true
